global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.1.39:9090','172.31.14.149:9100','172.31.2.229:9100','172.31.7.175:9100']
