global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.28.232:9090','172.31.23.187:9100','172.31.18.6:9100','172.31.18.188:9100']
